const date = new Date();
const ruby = [
    "I am running!",
    "Anyone wants icecream?",
    "I can play guitar all day",
    "Hihihi~",
    "Blue roses buquet are best afterall!",
    "Pusheen is so cute",
    "I am based in Ireland :)",
    "Liella! and Kessoku Band songs :)))",
    "Cool! I like animations too",
    "I hope the UI is easy to handle",
    "Have you ever balanced on a switch?",
    "It's hard to breathe with your tongue out",
    "You're doing great! I can't even cook.",
    "You're right. One day is not enough!",
    "I really miss the headphone jacks",
    "I can make friends easily!",
    "I'm a really good person xD",
    "fat fate stretches far",
    "Believe me",
    "Me! Poof yo!",
    "Ka~ na~ ko~ lo~ve~",
    "A friend gave me that pink snuggle-jumper",
    "I heard that time travelling is actually real!",
    "In the course I took up, I met a nice friend.",
    "I hope we can meet and talk",
    "Oh don't be! I don't like horror either.",
    "How many corners in the world?",
    "Pokemon and fire emblem!",
    "...jump!!!!!",
    "My pirate ship figure was handmade in Italy",
    "Love my m0M and p0Pzzz",
    "Coding realy passes time, its almost 2am",
    "I must have folded 1000 paper cranes",
    "My small team in f5 were really kind",
    "I've collected over thirthy 4-leaf clovers",
    "I miss my huawei phone",
    "The date is... " + date.getDate() + "." + (date.getMonth() + 1) + "." +  date.getFullYear() + ", time really flies!",
    "Join me!",
    "Light-mode took me 3 days! Do you like it?",
    "I gave up on making cursor animations",
    "Pixel and Lottiefile animations are lively!",
    "Smiles goes for miles!",
    "My Resume was made in Canva",
    "I can work onsite in Dublin and Cork",
    "I can work remotely anywhere",
]

export default ruby;