const date = new Date();
const ruby = [
    "I am running!",
    "Anyone wants icecream?",
    "I can play guitar all day",
    "My dream has a grand piano in it.",
    "Hihihi~",
    "Blue roses buquet are best afterall!",
    "Pusheen is so cute",
    "I am based in Ireland :)",
    "I wanna join a band",
    "This teacup is so pretty",
    "And chocolate cake and hot coco",
    "Liella! and Kessoku Band songs :)))",
    "My library of books with nice covers~",
    "Cool! I like animations too",
    "Let me introduce you to my shadow",
    "Say 'hi'........ FIVE!!",
    "I hope the UI is easy to handle",
    "Dogs... I want to raise one",
    "Have you ever balanced on a switch?",
    "It's hard to breathe with your tongue out",
    "20 degrees is already too hot!",
    "Wanna go Antarctica with me?",
    "I can only do 10 push ups",
    "You're doing great! I can't even cook.",
    "Don't cry. Hug!",
    "If I can backflip one day...one day",
    "You're right. One day is not enough!",
    "I really miss the headphone jacks",
    "Wooden boxes, small jars, thin pens",
    "One gift was all it took to start many hobbies",
    "I can make friends easily!",
    "I'm a really good person xD",
    "Make sure your fate is fat, so it stretches far",
    "Believe me",
    "Me! Poof yo!",
    "Ka~ na~ ko~ lo~ve~",
    "Pajamas are really comfortable",
    "A friend gave me that pink snuggle-jumper",
    "Driving alone will clear your mind",
    "I heard that time travelling is actually real!",
    "In the course I took up, I met a nice friend.",
    "I hope we can meet and talk",
    "Oh don't be! I don't like horror either.",
    "Green, red and brown are my favourite colors",
    "How many corners in the world?",
    "Pokemon and fire emblem!",
    "I wonder how far... wait step back aaand",
    "...jump!!!!!",
    "Dragons and witches... I want magic too",
    "My pirate ship figure was handmade in Italy",
    "Disneyland paris made me loose my voice",
    "I love my parents",
    "Coding realy passes time, its almost 2am",
    "I must have folded 1000 paper cranes",
    "My small team in f5 were really kind",
    "I've collected over thirthy 4-leaf clovers",
    "I broke my computer screen... ouch!",
    "I miss my huawei phone",
    "'Rymoquinn' was the name of my old car",
    "The date is... " + date.getDate() + "." + (date.getMonth() + 1) + "." +  date.getFullYear() + ", time really flies!",
    "Join me!",
    "Light-mode took me 3 days! Do you like it?",
    "I gave up on making cursor animations",
    "Pixel and Lottiefile animations are lively!",
    "Smiles goes for miles!",
]

export default ruby;