import LeftSide from '@/app/components/LeftSide'
import Navbar from '@/app/components/Navbar'
import RightSide from '@/app/components/RightSide'
import Head from 'next/head'

import { motion } from "framer-motion"
import Banner from '@/app/sections/Banner/Banner'
import About from '@/app/sections/About/About'
import Experience from '@/app/sections/Experience/Experience'
import Project from '@/app/sections/Projects/Project'
import Contact from '@/app/sections/Contact/Contact'
import Footer from '@/app/components/Footer'
import StarField from '@/app/components/background/StarField'
import StarJumps from '@/app/components/background/StarJumps'

export default function Home() {
  return (
    <>
      <Head>
        <title>Julia Rodrigo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/me/logo.png" />

      </Head>
      <main className='relative w-full h-screen font-bodyFont dark:bg-bodyColor bg-bgColor text-textLight overflow-x-hidden sm:overflow-y-scroll overflow-y-hidden scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60'>
        
        <div className='dark:hidden inline-block absolute w-full h-screen'>
          <StarField />
          <StarJumps />
        </div>

        <Navbar />

        <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
          <motion.div
          
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}

            className='hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0'
          >
            <LeftSide />
          </motion.div>
          <div className='h-[88vh] mx-auto p-4 z-10'>
            <Banner />
            <About />
            <Experience />
            <Project />
            <Contact />
            <Footer />

          </div>
          <motion.div
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            
            className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0 mr-5 '
          >
          <RightSide />
          </motion.div>
        </div>
      </main>
    </>
  )
}
